filter:
    excluded_paths:
        - "extra/"
        - "tests/"
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=test/Test.php
                coverage:
                    file: my-coverage-file
                    format: php-clover
